services:
  mongodb:
    image: mongo
    ports:
      - 27017
    volumes:
      - data:/mongodb
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - '8080:8080'
    volumes:
      - ./src:/usr/app/src
    command: yarn start:dev
    environment: 
      - SP_CLIENT_ID=${SP_CLIENT_ID}
      - SP_CLIENT_SECRET=${SP_CLIENT_SECRET}
      - CALLBACK_URL=${CALLBACK_URL}
volumes:
  data:
